version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "_ide_helper.php",
  ".phpstorm.meta.php"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

[[analyzers]]
name = "php"
enabled = true
