name: Build production

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build vite

    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install modules
        run: npm install

      - name: Build code
        run: npm run build --if-present

      - name: Commit build
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: New production build
          branch: ${{ github.ref_name }}
