name: Code Style

on: [push, pull_request]

jobs:
  ESLint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Install modules
        run: npm install 
      
      - name: Run ESLint
        run: npm run lint
        
        
  PHP-CS-Fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php_cs.dist.php --allow-risky=yes

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
            commit_message: PHP Fix styling
            branch: ${{ steps.extract_branch.outputs.branch }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
