name: Code Style

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  js-code-style:
    name: ES-Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install modules
        run: npm install

      - name: Run ESLint
        run: npm run lint-fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: JS Fix styling


  php-code-style:
    name: PHP-CS Fixer

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php_cs.dist.php --allow-risky=yes

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: PHP Fix styling



  pull-request:
    name: Create pull request

    runs-on: ubuntu-latest

    needs:
      - js-code-style
      - php-code-style

    if: ${{ success() }}

    outputs:
      id: ${{ steps.branch.outputs.pr_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          pr_title: merge ${{ github.ref_name }} into main
          github_token: ${{ secrets.GITHUB_TOKEN }}



  build:
    name: Build vite

    runs-on: ubuntu-latest

    needs:
      - pull-request

    if: ${{ success() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.pull-request.outputs.id }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install modules
        run: npm install

      - name: Build code
        run: npm run build --if-present

      - name: Commit Build
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: New vite build from ${{ needs.pull-request.outputs.branch-name }}
