name: Deployment

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  js-code-style:
    name: ES-Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install modules
        run: npm install

      - name: Run ESLint
        run: npm run lint-fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: JS Fix styling
          branch: ${{ github.ref_name }}


  php-code-style:
    name: PHP-CS Fixer

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php_cs.dist.php --allow-risky=yes

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Fix styling
          branch: ${{ github.ref_name }}



  pull-request:
    name: Create pull request

    runs-on: ubuntu-latest

    needs:
      - js-code-style
      - php-code-style

    if: ${{ success() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Reset branch
        run: |
          git fetch origin ${{ github.ref_name }}:${{ github.ref_name }}
          git reset --hard ${{ github.ref_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: merge-${{ github.ref_name }}
          title: merge ${{ github.ref_name }} into main
          delete-branch: true


  build:
    name: Build vite

    runs-on: ubuntu-latest

    needs:
      - pull-request

    if: ${{ success() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: merge-${{ github.ref_name }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install modules
        run: npm install

      - name: Build code
        run: npm run build --if-present

      - name: Commit Build
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Created a new vite build from commit ${{ github.event.head_commit.message }}
          branch: merge-${{ github.ref_name }}
