name: JS Code Style

on: [push]

jobs:
  ESLint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Install modules
        run: yarn 
      
      - name: Run ESLint
        run: ./node_modules/.bin/eslint resources/admin --ext .js,.vue
