name: JS Code Style

on: [push]

jobs:
  eslint-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Install modules
        run: yarn install 
      
      - name: Run ESLint
        run: yarn run eslint resources/admin --ext .js,.vue
